#ifndef SM64AP_H
#define SM64AP_H

#include <stdbool.h>

#ifdef __cplusplus
#define AP_EXTERN_C extern "C"
#else
#define AP_EXTERN_C
#endif

#ifdef __cplusplus
extern "C" {
    #include "types.h"
}
#else
#include "types.h"
#endif

#define SM64AP_ID_OFFSET 3626000
#define SM64AP_ITEMID_STAR SM64AP_ID_OFFSET
#define SM64AP_ID_KEY1 (SM64AP_ID_OFFSET+178)
#define SM64AP_ID_KEY2 (SM64AP_ID_KEY1+1)
#define SM64AP_ID_KEYPROG (SM64AP_ID_KEY2+1)
#define SM64AP_ID_WINGCAP (SM64AP_ID_KEYPROG+1)
#define SM64AP_ID_METALCAP (SM64AP_ID_WINGCAP+1)
#define SM64AP_ID_VANISHCAP (SM64AP_ID_METALCAP+1)
#define SM64AP_ITEMID_1UP (SM64AP_ID_VANISHCAP+1)

#define SM64AP_ABILITY_OFFSET (SM64AP_ITEMID_1UP+1)
#define SM64AP_ID_DOUBLEJUMP (SM64AP_ABILITY_OFFSET)
#define SM64AP_ID_TRIPLEJUMP (SM64AP_ABILITY_OFFSET+1)
#define SM64AP_ID_LONGJUMP (SM64AP_ABILITY_OFFSET+2)
#define SM64AP_ID_BACKFLIP (SM64AP_ABILITY_OFFSET+3)
#define SM64AP_ID_SIDEFLIP (SM64AP_ABILITY_OFFSET+4)
#define SM64AP_ID_WALLKICK (SM64AP_ABILITY_OFFSET+5)
#define SM64AP_ID_DIVE (SM64AP_ABILITY_OFFSET+6)
#define SM64AP_ID_GROUNDPOUND (SM64AP_ABILITY_OFFSET+7)
#define SM64AP_ID_KICK (SM64AP_ABILITY_OFFSET+8)
#define SM64AP_ID_CLIMB (SM64AP_ABILITY_OFFSET+9)
#define SM64AP_ID_LEDGEGRAB (SM64AP_ABILITY_OFFSET+10)

#define SM64AP_ID_CANNONUNLOCK(x) (SM64AP_ID_OFFSET+200+x)
#define SM64AP_ID_PAINTINGUNLOCK(x) (SM64AP_ID_OFFSET+230+x)
#define SM64AP_ID_ABILITY(x) (SM64AP_ABILITY_OFFSET+x)
// Reserving some room for coins, if needed
// Nice filler
#define SM64AP_ID_1_HEALTH_PIP   (SM64AP_ID_OFFSET+1750)
#define SM64AP_ID_2_HEALTH_PIP   (SM64AP_ID_OFFSET+1751)
#define SM64AP_ID_3_HEALTH_PIP   (SM64AP_ID_OFFSET+1752)
#define SM64AP_ID_4_HEALTH_PIP   (SM64AP_ID_OFFSET+1753)
#define SM64AP_ID_FULL_REFILL    (SM64AP_ID_OFFSET+1754)
// Traps
#define SM64AP_ID_BONK_TRAP      (SM64AP_ID_OFFSET+1760)
#define SM64AP_ID_FIRE_TRAP      (SM64AP_ID_OFFSET+1761)
#define SM64AP_ID_ELEC_TRAP      (SM64AP_ID_OFFSET+1762)
#define SM64AP_ID_CHUCK_TRAP     (SM64AP_ID_OFFSET+1763)
#define SM64AP_ID_SPIN_TRAP      (SM64AP_ID_OFFSET+1764)
#define SM64AP_ID_GUST_TRAP      (SM64AP_ID_OFFSET+1765)
#define SM64AP_ID_UNCOLLECT_COIN_TRAP (SM64AP_ID_OFFSET+1766)


#define SM64AP_LOCATIONID_BOARDBOWSERSSUB (SM64AP_ID_OFFSET + 56)
#define SM64AP_LOCATIONID_BASEMENTTOAD (SM64AP_ID_OFFSET + 168)
#define SM64AP_LOCATIONID_SECONDFLOORTOAD (SM64AP_LOCATIONID_BASEMENTTOAD + 1)
#define SM64AP_LOCATIONID_THIRDFLOORTOAD (SM64AP_LOCATIONID_SECONDFLOORTOAD + 1)
#define SM64AP_LOCATIONID_MIPS1 (SM64AP_LOCATIONID_THIRDFLOORTOAD + 1)
#define SM64AP_LOCATIONID_MIPS2 (SM64AP_LOCATIONID_MIPS1 + 1)
#define SM64AP_LOCATIONID_YOSHI (SM64AP_ID_OFFSET + 244)
#define SM64AP_LOCATIONID_MOAT_DRAIN (SM64AP_ID_OFFSET + 245)
#define SM64AP_LOCATIONID_COIN_CHECK_START 3627000
#define SM64AP_NUM_MAIN_COIN_CHECKS 2091
#define SM64AP_NUM_SECRET_COIN_CHECKS 565
#define SM64AP_NUM_COIN_CHECKS (SM64AP_NUM_MAIN_COIN_CHECKS + SM64AP_NUM_SECRET_COIN_CHECKS)
#define SM64AP_LOCATIONID_COIN_CHECK_END (SM64AP_LOCATIONID_COIN_CHECK_START + SM64AP_NUM_MAIN_COIN_CHECKS - 1)
#define SM64AP_LOCATIONID_1UP_CHECK_START 3629100
#define SM64AP_NUM_1UP_CHECKS 93
#define SM64AP_LOCATIONID_1UP_CHECK_END (SM64AP_LOCATIONID_1UP_CHECK_START + SM64AP_NUM_1UP_CHECKS - 1)
#define SM64AP_LOCATIONID_SECRET_COIN_CHECK_START (SM64AP_LOCATIONID_1UP_CHECK_END + 1)
#define SM64AP_LOCATIONID_SECRET_COIN_CHECK_END (SM64AP_LOCATIONID_SECRET_COIN_CHECK_START + SM64AP_NUM_SECRET_COIN_CHECKS - 1)
#define SM64AP_LOCATIONID_BLOCKSANITY_START (SM64AP_LOCATIONID_SECRET_COIN_CHECK_END + 1)
#define SM64AP_NUM_BLOCKSANITY_CHECKS 103
#define SM64AP_LOCATIONID_BLOCKSANITY_END (SM64AP_LOCATIONID_BLOCKSANITY_START + SM64AP_NUM_BLOCKSANITY_CHECKS - 1)

#define SM64AP_NUM_LOCS (SM64AP_LOCATIONID_BLOCKSANITY_END - SM64AP_ID_OFFSET + 1)

#define SM64AP_NUM_ABILITIES 11
#define SM64AP_NUM_PAINTING_LOCKS 15

enum {
    SM64AP_FEATURE_BOB_KING_BOBOMB,
    SM64AP_FEATURE_BOB_KOOPA_THE_QUICK,
    SM64AP_FEATURE_BOB_BOBOMB_BUDDY,
    SM64AP_FEATURE_WF_WHOMP_KING,
    SM64AP_FEATURE_WF_FORTRESS,
    SM64AP_FEATURE_WF_BOBOMB_BUDDY,
    SM64AP_FEATURE_WF_HOOT,
    SM64AP_FEATURE_CCM_SNOWMANS_BODY,
    SM64AP_FEATURE_CCM_BIG_PENGUIN,
    SM64AP_FEATURE_JRB_SUNKEN_SHIP,
    SM64AP_FEATURE_JRB_RAISED_SHIP,
    SM64AP_FEATURE_JRB_BOBOMB_BUDDY,
    SM64AP_FEATURE_JRB_JET_STREAM,
    SM64AP_FEATURE_JRB_UNAGI,
    SM64AP_FEATURE_LLL_KOOPA_SHELL,
    SM64AP_FEATURE_SSL_KLEPTO_STAR,
    SM64AP_FEATURE_THI_KOOPA_THE_QUICK,
    SM64AP_FEATURE_TTM_UKIKI,
    SM64AP_FEATURE_DDD_MANTA_RAY,
    SM64AP_FEATURE_DDD_BOWSERS_SUB,
    SM64AP_FEATURE_DDD_POLES,
    SM64AP_FEATURE_BBH_STAIRCASE,
    SM64AP_FEATURE_BBH_MERRY_GO_ROUND,
    SM64AP_NUM_FEATURES
};

#define SM64AP_FEATURE_OFFSET SM64AP_ID_PAINTINGUNLOCK(SM64AP_NUM_PAINTING_LOCKS)
#define SM64AP_ID_FEATURE(x) (SM64AP_FEATURE_OFFSET + (x))

#define SM64AP_CASTLE_KEY_FIRST_FLOOR 0
#define SM64AP_CASTLE_KEY_BASEMENT 1
#define SM64AP_CASTLE_KEY_BASEMENT_STAR 2
#define SM64AP_CASTLE_KEY_UPSTAIRS 3
#define SM64AP_CASTLE_KEY_50_STAR 4
#define SM64AP_CASTLE_KEY_70_STAR 5
#define SM64AP_NUM_CASTLE_KEYS 6

#define SM64AP_CASTLE_KEY_OFFSET (SM64AP_FEATURE_OFFSET + SM64AP_NUM_FEATURES)
#define SM64AP_ID_FIRST_FLOOR_KEY (SM64AP_CASTLE_KEY_OFFSET)
#define SM64AP_ID_BASEMENT_KEYPROG (SM64AP_CASTLE_KEY_OFFSET + 1)
#define SM64AP_ID_UPSTAIRS_KEYPROG (SM64AP_CASTLE_KEY_OFFSET + 2)
#define SM64AP_NUM_CASTLE_KEY_ITEMS 3

#define SM64AP_CASTLE_MISC_OFFSET (SM64AP_CASTLE_KEY_OFFSET + SM64AP_NUM_CASTLE_KEY_ITEMS)
#define SM64AP_ID_PROGRESSIVE_MIPS (SM64AP_CASTLE_MISC_OFFSET)
#define SM64AP_ID_WING_CAP_LIGHT (SM64AP_CASTLE_MISC_OFFSET + 1)
#define SM64AP_ID_BBH (SM64AP_CASTLE_MISC_OFFSET + 2)
#define SM64AP_ID_TOADS (SM64AP_CASTLE_MISC_OFFSET + 3)
#define SM64AP_ID_CASTLE_CANNON (SM64AP_CASTLE_MISC_OFFSET + 4)
#define SM64AP_ID_YOSHI (SM64AP_CASTLE_MISC_OFFSET + 5)
#define SM64AP_NUM_CASTLE_MISC_ITEMS 6

#define SM64AP_ID_BITFS 3626304

#define SM64AP_LEVEL_CAP_OFFSET (SM64AP_CASTLE_MISC_OFFSET + SM64AP_NUM_CASTLE_MISC_ITEMS)

enum {
    SM64AP_LEVEL_CAP_BOB_WING,
    SM64AP_LEVEL_CAP_CASTLE_WING,
    SM64AP_LEVEL_CAP_LLL_WING,
    SM64AP_LEVEL_CAP_SSL_WING,
    SM64AP_LEVEL_CAP_TOTWC_WING,
    SM64AP_LEVEL_CAP_WMOTR_WING,
    SM64AP_LEVEL_CAP_WF_METAL,
    SM64AP_LEVEL_CAP_JRB_METAL,
    SM64AP_LEVEL_CAP_HMC_METAL,
    SM64AP_LEVEL_CAP_DDD_METAL,
    SM64AP_LEVEL_CAP_WDW_METAL,
    SM64AP_LEVEL_CAP_COTMC_METAL,
    SM64AP_LEVEL_CAP_BITDW_METAL,
    SM64AP_LEVEL_CAP_BBH_VANISH,
    SM64AP_LEVEL_CAP_DDD_VANISH,
    SM64AP_LEVEL_CAP_SL_VANISH,
    SM64AP_LEVEL_CAP_VCUTM_VANISH,
    SM64AP_LEVEL_CAP_WDW_VANISH,
    SM64AP_NUM_LEVEL_CAPS
};

#define SM64AP_ID_LEVEL_CAP(x) (SM64AP_LEVEL_CAP_OFFSET + (x))

#define SM64AP_OBJECT_ITEM_OFFSET (SM64AP_LEVEL_CAP_OFFSET + SM64AP_NUM_LEVEL_CAPS)

enum {
    SM64AP_OBJECT_ITEM_HMC_SWIMMING_BEAST,
    SM64AP_OBJECT_ITEM_RR_CARPETS,
    SM64AP_OBJECT_ITEM_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_THI_WARP_PIPES,
    SM64AP_OBJECT_ITEM_CCM_BABY_PENGUINS,
    SM64AP_OBJECT_ITEM_SL_PENGUIN,
    SM64AP_OBJECT_ITEM_SSL_PYRAMID_ELEVATOR,
    SM64AP_OBJECT_ITEM_ROLLING_LOGS,
    SM64AP_OBJECT_ITEM_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_RESERVED_BITFS,
    SM64AP_OBJECT_ITEM_WDW_WATER_LEVEL_DIAMONDS,
    SM64AP_OBJECT_ITEM_BOB_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_WF_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_LLL_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_HMC_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_VCUTM_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_LLL_ROLLING_LOGS,
    SM64AP_OBJECT_ITEM_TTM_ROLLING_LOGS,
    SM64AP_OBJECT_ITEM_BOB_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_HMC_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_WDW_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_RR_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_BITDW_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_BITS_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_TTC_SPINNERS,
    SM64AP_NUM_CONTIGUOUS_OBJECT_ITEMS,
    SM64AP_OBJECT_ITEM_JRB_PURPLE_SWITCHES = SM64AP_NUM_CONTIGUOUS_OBJECT_ITEMS,
    SM64AP_OBJECT_ITEM_DDD_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_TTM_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_THI_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_CCM_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_SSL_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_SL_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_WDW_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_TTM_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_THI_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_RR_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_WMOTR_BOBOMB_BUDDY,
    SM64AP_OBJECT_ITEM_GLOBAL_BOBOMB_BUDDIES,
    SM64AP_OBJECT_ITEM_JRB_TREASURE_CHESTS,
    SM64AP_OBJECT_ITEM_DDD_TREASURE_CHESTS,
    SM64AP_OBJECT_ITEM_GLOBAL_TREASURE_CHESTS,
    SM64AP_OBJECT_ITEM_BITDW_WARP_PIPES,
    SM64AP_OBJECT_ITEM_BITFS_WARP_PIPES,
    SM64AP_OBJECT_ITEM_BITS_WARP_PIPES,
    SM64AP_OBJECT_ITEM_GLOBAL_WARP_PIPES,
    SM64AP_NUM_OBJECT_ITEMS
};

#define SM64AP_ID_OBJECT_ITEM(x) (SM64AP_OBJECT_ITEM_OFFSET + (x))

#define SM64AP_ID_HAT 3626320
#define SM64AP_ID_JRB_PURPLE_SWITCHES 3626321
#define SM64AP_ID_DDD_PURPLE_SWITCHES 3626322
#define SM64AP_ID_TTM_PURPLE_SWITCHES 3626323
#define SM64AP_ID_THI_PURPLE_SWITCHES 3626324
#define SM64AP_ID_CCM_BOBOMB_BUDDY 3626920
#define SM64AP_ID_SSL_BOBOMB_BUDDY 3626921
#define SM64AP_ID_SL_BOBOMB_BUDDY 3626922
#define SM64AP_ID_WDW_BOBOMB_BUDDY 3626923
#define SM64AP_ID_TTM_BOBOMB_BUDDY 3626924
#define SM64AP_ID_THI_BOBOMB_BUDDY 3626925
#define SM64AP_ID_RR_BOBOMB_BUDDY 3626926
#define SM64AP_ID_WMOTR_BOBOMB_BUDDY 3626927
#define SM64AP_ID_GLOBAL_BOBOMB_BUDDIES 3626928
#define SM64AP_ID_JRB_TREASURE_CHESTS 3626929
#define SM64AP_ID_DDD_TREASURE_CHESTS 3626930
#define SM64AP_ID_GLOBAL_TREASURE_CHESTS 3626931
#define SM64AP_ID_BITDW_WARP_PIPES 3626932
#define SM64AP_ID_BITFS_WARP_PIPES 3626933
#define SM64AP_ID_BITS_WARP_PIPES 3626934
#define SM64AP_ID_GLOBAL_WARP_PIPES 3626935
#define SM64AP_ID_WMOTR_CANNON 3626525
#define SM64AP_LOCATIONID_WMOTR_BOBOMB_BUDDY SM64AP_ID_WMOTR_CANNON
#define SM64AP_ID_VCUTM_ENTRANCE 3626555
#define SM64AP_ID_BOWSER_STAGE_1UPS 3626556
#define SM64AP_ID_BITDW_1UPS 3626557
#define SM64AP_ID_BITFS_1UPS 3626558
#define SM64AP_ID_THI_TINY_PAINTING 3626242
#define SM64AP_ID_THI_HUGE_PAINTING 3626559
#define SM64AP_ID_PROGRESSIVE_BOWSER_ARENA_BOMB 3626849
#define SM64AP_ID_BITDW_PROGRESSIVE_BOWSER_ARENA_BOMB 3626850
#define SM64AP_ID_BITFS_PROGRESSIVE_BOWSER_ARENA_BOMB 3626851
#define SM64AP_ID_BITS_PROGRESSIVE_BOWSER_ARENA_BOMB 3626852
#define SM64AP_ID_RR_LEVEL_UNLOCK 3626853
#define SM64AP_ID_WMOTR_LEVEL_UNLOCK 3626854

#define SM64AP_ONE_UP_GLOBAL_ITEM_OFFSET 3626855
#define SM64AP_ID_GLOBAL_FREESTANDING_1UPS (SM64AP_ONE_UP_GLOBAL_ITEM_OFFSET + 0)
#define SM64AP_ID_GLOBAL_TRIGGER_1UPS (SM64AP_ONE_UP_GLOBAL_ITEM_OFFSET + 1)
#define SM64AP_ID_GLOBAL_1UP_BLOCKS (SM64AP_ONE_UP_GLOBAL_ITEM_OFFSET + 2)
#define SM64AP_ID_GLOBAL_BUTTERFLIES 3626919
#define SM64AP_NUM_ONE_UP_CATEGORIES 4

#define SM64AP_ONE_UP_LEVEL_ITEM_OFFSET 3626858
#define SM64AP_NUM_ONE_UP_LEVEL_ITEMS 61
#define SM64AP_ONE_UP_LEVEL_ITEM_END \
    (SM64AP_ONE_UP_LEVEL_ITEM_OFFSET + SM64AP_NUM_ONE_UP_LEVEL_ITEMS - 1)

enum {
    SM64AP_ONE_UP_CATEGORY_FREESTANDING,
    SM64AP_ONE_UP_CATEGORY_TRIGGER,
    SM64AP_ONE_UP_CATEGORY_BLOCK,
    SM64AP_ONE_UP_CATEGORY_BUTTERFLY,
};

/*
 * Coin-source items are intentionally outside the older contiguous item
 * ranges so adding them does not renumber any existing item.
 */
#define SM64AP_COIN_GLOBAL_ITEM_OFFSET 3626560
#define SM64AP_COIN_LEVEL_ITEM_OFFSET 3626600

enum {
    SM64AP_COIN_SOURCE_YELLOW_COIN,
    SM64AP_COIN_SOURCE_RED_COIN,
    SM64AP_COIN_SOURCE_MOVING_BLUE_COIN,
    SM64AP_COIN_SOURCE_BLUE_COIN_SWITCH,
    SM64AP_COIN_SOURCE_HORIZONTAL_LINE,
    SM64AP_COIN_SOURCE_HORIZONTAL_RING,
    SM64AP_COIN_SOURCE_ARROW,
    SM64AP_COIN_SOURCE_VERTICAL_LINE,
    SM64AP_COIN_SOURCE_VERTICAL_RING,
    SM64AP_COIN_SOURCE_BOBOMB,
    SM64AP_COIN_SOURCE_BOO,
    SM64AP_COIN_SOURCE_BULLY,
    SM64AP_COIN_SOURCE_CHUCKYA,
    SM64AP_COIN_SOURCE_ENEMY_LAKITU,
    SM64AP_COIN_SOURCE_EYEROK,
    SM64AP_COIN_SOURCE_FIRE_PIRANHA_PLANT,
    SM64AP_COIN_SOURCE_FLY_GUY,
    SM64AP_COIN_SOURCE_FLYING_BOOKEND,
    SM64AP_COIN_SOURCE_GOOMBA,
    SM64AP_COIN_SOURCE_KOOPA_TROOPA,
    SM64AP_COIN_SOURCE_MONEYBAG,
    SM64AP_COIN_SOURCE_MR_BLIZZARD,
    SM64AP_COIN_SOURCE_MR_I,
    SM64AP_COIN_SOURCE_MONTY_MOLE,
    SM64AP_COIN_SOURCE_BIG_BULLY,
    SM64AP_COIN_SOURCE_PIRANHA_PLANT,
    SM64AP_COIN_SOURCE_POKEY,
    SM64AP_COIN_SOURCE_SCUTTLEBUG,
    SM64AP_COIN_SOURCE_SKEETER,
    SM64AP_COIN_SOURCE_SNUFIT,
    SM64AP_COIN_SOURCE_SPINDRIFT,
    SM64AP_COIN_SOURCE_SWOOP,
    SM64AP_COIN_SOURCE_WHOMP,
    SM64AP_COIN_SOURCE_ONE_COIN_BOX,
    SM64AP_COIN_SOURCE_THREE_COIN_BOX,
    SM64AP_COIN_SOURCE_TEN_COIN_BOX,
    SM64AP_COIN_SOURCE_BREAKABLE_COIN_BOX,
    SM64AP_COIN_SOURCE_SMALL_BREAKABLE_BOX,
    SM64AP_COIN_SOURCE_JUMPING_BOX,
    SM64AP_COIN_SOURCE_WOODEN_POST,
    SM64AP_COIN_SOURCE_BOWSER_PUZZLE,
    SM64AP_COIN_SOURCE_BIG_BOO,
    SM64AP_COIN_SOURCE_THWOMP,
    SM64AP_NUM_COIN_SOURCES
};

#define SM64AP_NUM_LEVEL_MOVES 10

enum {
    SM64AP_LEVEL_MOVE_TRIPLE_JUMP,
    SM64AP_LEVEL_MOVE_LONG_JUMP,
    SM64AP_LEVEL_MOVE_BACKFLIP,
    SM64AP_LEVEL_MOVE_SIDE_FLIP,
    SM64AP_LEVEL_MOVE_WALL_KICK,
    SM64AP_LEVEL_MOVE_DIVE,
    SM64AP_LEVEL_MOVE_GROUND_POUND,
    SM64AP_LEVEL_MOVE_KICK,
    SM64AP_LEVEL_MOVE_CLIMB,
    SM64AP_LEVEL_MOVE_LEDGE_GRAB,
};

enum {
    SM64AP_LEVEL_MOVE_AREA_BOB,
    SM64AP_LEVEL_MOVE_AREA_WF,
    SM64AP_LEVEL_MOVE_AREA_JRB,
    SM64AP_LEVEL_MOVE_AREA_CCM,
    SM64AP_LEVEL_MOVE_AREA_BBH,
    SM64AP_LEVEL_MOVE_AREA_HMC,
    SM64AP_LEVEL_MOVE_AREA_LLL,
    SM64AP_LEVEL_MOVE_AREA_SSL,
    SM64AP_LEVEL_MOVE_AREA_DDD,
    SM64AP_LEVEL_MOVE_AREA_SL,
    SM64AP_LEVEL_MOVE_AREA_WDW,
    SM64AP_LEVEL_MOVE_AREA_TTM,
    SM64AP_LEVEL_MOVE_AREA_THI,
    SM64AP_LEVEL_MOVE_AREA_TTC,
    SM64AP_LEVEL_MOVE_AREA_RR,
    SM64AP_LEVEL_MOVE_AREA_CASTLE,
    SM64AP_LEVEL_MOVE_AREA_BITDW,
    SM64AP_LEVEL_MOVE_AREA_BITFS,
    SM64AP_LEVEL_MOVE_AREA_BITS,
    SM64AP_LEVEL_MOVE_AREA_VCUTM,
    SM64AP_NUM_LEVEL_MOVE_AREAS
};

#define SM64AP_LEVEL_MOVE_OFFSET 3626325
#define SM64AP_ID_LEVEL_MOVE(area, move) (SM64AP_LEVEL_MOVE_OFFSET + ((area) * SM64AP_NUM_LEVEL_MOVES) + (move))
#define SM64AP_ID_LEVEL_MOVE_END SM64AP_ID_LEVEL_MOVE(SM64AP_NUM_LEVEL_MOVE_AREAS - 1, SM64AP_NUM_LEVEL_MOVES - 1)

enum {
    SM64AP_1UP_SOURCE_OBJECT,
    SM64AP_1UP_SOURCE_SLIDING,
    SM64AP_1UP_SOURCE_JUMP_ON_APPROACH,
    SM64AP_1UP_SOURCE_HIDDEN,
    SM64AP_1UP_SOURCE_HIDDEN_POLE,
    SM64AP_1UP_SOURCE_BOX,
    SM64AP_1UP_SOURCE_BUTTERFLY,
    SM64AP_1UP_SOURCE_MONTY_MOLES,
    SM64AP_1UP_SOURCE_WALKING,
    SM64AP_1UP_SOURCE_RUNNING_AWAY,
};

#define SM64AP_CASTLE_DOOR_FIRST_FLOOR 0xF0
#define SM64AP_CASTLE_DOOR_BASEMENT_STAR 0xF1
#define SM64AP_CASTLE_DOOR_UPSTAIRS_50 0xF2
#define SM64AP_CASTLE_DOOR_UPSTAIRS_70 0xF3

#define SM64AP_ENTRANCE_ID(level, variant) ((level) * 10 + (variant))
#define SM64AP_ENTRANCE_WDW_LOW 1
#define SM64AP_ENTRANCE_WDW_MIDDLE 2
#define SM64AP_ENTRANCE_WDW_HIGH 3
#define SM64AP_WDW_LOW_ENTRY_MAX 1382.4f
#define SM64AP_WDW_HIGH_ENTRY_MIN 1600.0f
#define SM64AP_WDW_LOW_WATER_LEVEL 31
#define SM64AP_WDW_MIDDLE_WATER_LEVEL 1024
#define SM64AP_WDW_HIGH_WATER_LEVEL 2816
#define SM64AP_ENTRANCE_TTC_STOPPED 1
#define SM64AP_ENTRANCE_TTC_SLOW 2
#define SM64AP_ENTRANCE_TTC_RANDOM 3
#define SM64AP_ENTRANCE_TTC_FAST 4

//Init
AP_EXTERN_C void SM64AP_InitMW(const char*, const char*, const char*);
AP_EXTERN_C void SM64AP_InitSP(const char*);

// Local Stars, Keys and Caps
AP_EXTERN_C int SM64AP_GetStars();
AP_EXTERN_C int SM64AP_GetRequiredStars(int);
AP_EXTERN_C int SM64AP_GetCoinStarRequirement(int);
AP_EXTERN_C u32 SM64AP_CourseStarFlags(s32);
AP_EXTERN_C void SM64AP_RedirectWarp(s16*,s16*,s8*,s16*,s16*,bool,int,s32);
AP_EXTERN_C int SM64AP_EntranceToTTC();
AP_EXTERN_C void SM64AP_SetClockToTTCAction(int* action);
AP_EXTERN_C void SM64AP_SetClockToTTCState();
AP_EXTERN_C void SM64AP_SetTTCEntranceSpeed(int speed);
AP_EXTERN_C int SM64AP_GetTTCEntranceVariant();
AP_EXTERN_C s16 SM64AP_GetWDWEntranceWaterLevel(s16 vanillaWaterLevel);
// Returns a comma-separated list of short entrance names (e.g. "BOB, PSS, LLL") describing which
// vanilla entrance(s) now lead to destLevel under Area Rando, or "" if there's nothing to report
// (Area Rando inactive, destLevel not shuffled, or destLevel is Bowser in the Sky).
AP_EXTERN_C const char *SM64AP_GetAreaRandoSpoiler(s16 destLevel);
AP_EXTERN_C s16 SM64AP_ResolveAreaMusic(s16 level, s16 area, s16 vanillaSeq);
AP_EXTERN_C void SM64AP_SelectSkybox(s16 level, s16 area, s16 vanillaSkybox);
AP_EXTERN_C s16 SM64AP_ResolveSkyboxBackground(s16 vanillaSkybox);
AP_EXTERN_C bool SM64AP_CheckedLoc(int);
AP_EXTERN_C void SM64AP_CheckCoinCount(int, int);
AP_EXTERN_C bool SM64AP_OneUpChecksEnabled();
AP_EXTERN_C bool SM64AP_BuddyChecksEnabled();
AP_EXTERN_C int SM64AP_ResolveOneUpLocation(s16, s16, s16, s16, s16, s16, s16);
AP_EXTERN_C bool SM64AP_ShouldSuppressOneUp(int);
AP_EXTERN_C bool SM64AP_CollectOneUp(int);
AP_EXTERN_C bool SM64AP_HaveOneUpSource(s16, s16);
AP_EXTERN_C int SM64AP_LevelOneUpUnlockCount(s16);
AP_EXTERN_C const char *SM64AP_LevelOneUpUnlockName(s16, s16);
AP_EXTERN_C bool SM64AP_LevelOneUpUnlockEnabled(s16, s16);
AP_EXTERN_C int SM64AP_BowserArenaBombCount(s16);
AP_EXTERN_C void SM64AP_SendBlocksanityCheck(s16, s16, s32, s16, s16, s16);
AP_EXTERN_C bool SM64AP_ShouldSpawnBowserStageOneUp(s16, s16, u32);
AP_EXTERN_C bool SM64AP_HaveKey1();
AP_EXTERN_C bool SM64AP_HaveKey2();
AP_EXTERN_C bool SM64AP_HaveCastleKey(int);
AP_EXTERN_C bool SM64AP_HaveProgressiveMips(int);
AP_EXTERN_C int SM64AP_MipsSpawnTier(void);
AP_EXTERN_C bool SM64AP_HaveWingCapLight();
AP_EXTERN_C bool SM64AP_HaveBBH();
AP_EXTERN_C bool SM64AP_HaveToads();
AP_EXTERN_C bool SM64AP_HaveCastleCannon();
AP_EXTERN_C bool SM64AP_HaveWmotrCannon();
AP_EXTERN_C bool SM64AP_HaveYoshi();
AP_EXTERN_C bool SM64AP_HaveBITFS();
AP_EXTERN_C bool SM64AP_HaveHat();
AP_EXTERN_C bool SM64AP_HaveBowserStageExtraOneUps(s16);
AP_EXTERN_C bool SM64AP_HaveVcutmEntrance();
AP_EXTERN_C bool SM64AP_HatRestoreWithAnimationPending();
AP_EXTERN_C bool SM64AP_HatRestoreWithoutAnimationPending();
AP_EXTERN_C void SM64AP_HatRestoreComplete();
AP_EXTERN_C bool SM64AP_HaveCap(int);
AP_EXTERN_C bool SM64AP_HaveAnyCap(int);
AP_EXTERN_C int SM64AP_CountLevelCaps(int);
AP_EXTERN_C bool SM64AP_HaveGlobalCap(int);
AP_EXTERN_C bool SM64AP_ShowGlobalCapDisplay();
AP_EXTERN_C bool SM64AP_HaveCannon(int);
AP_EXTERN_C bool SM64AP_HaveFeature(int);
AP_EXTERN_C bool SM64AP_HaveObjectItem(int);
AP_EXTERN_C bool SM64AP_HaveObjectItemForCourse(int, int);
AP_EXTERN_C bool SM64AP_HaveObjectItemForLevel(int, s16);
AP_EXTERN_C bool SM64AP_HaveCoinSource(int, s16);
AP_EXTERN_C int SM64AP_LevelCoinUnlockCount(s16, bool);
AP_EXTERN_C const char *SM64AP_LevelCoinUnlockName(s16, bool, int);
AP_EXTERN_C bool SM64AP_LevelCoinUnlockEnabled(s16, bool, int);
AP_EXTERN_C bool SM64AP_HaveLevelCapOrGlobal(int);
AP_EXTERN_C int SM64AP_LevelMoveAreaForLevel(s16);
AP_EXTERN_C bool SM64AP_HaveLevelMoveOrGlobal(int, int);
AP_EXTERN_C bool SM64AP_CollectedCourseStar(int, int);
AP_EXTERN_C u32 SM64AP_ServerSaveFlags();
AP_EXTERN_C void SM64AP_SetServerSaveFlags(u32);
AP_EXTERN_C void SM64AP_ClearServerSaveFlags(u32);
AP_EXTERN_C u32 SM64AP_ServerCannonFlags();
AP_EXTERN_C void SM64AP_SetServerCannonFlag(int);
AP_EXTERN_C int SM64AP_ServerCoinHighScore(int);
AP_EXTERN_C void SM64AP_SetServerCoinHighScore(int, int);
AP_EXTERN_C void SM64AP_SetMarioHeadColors(u8, u8, u8, u8, u8, u8, u8, u8, u8);
AP_EXTERN_C void SM64AP_ApplyMarioHeadColors(void);
AP_EXTERN_C bool SM64AP_ShouldSpawnLevelObject(s16, s16, s16, s16, s16, s16, u32, const void *);
AP_EXTERN_C int SM64AP_BowserHitRequirement(s16);
AP_EXTERN_C int SM64AP_BowserInTheSkyStageCollapseHits();
AP_EXTERN_C bool SM64AP_ShouldCreateWhirlpool(s16, s16, s8, s8, s16, s16, s16, s16);
AP_EXTERN_C bool SM64AP_HavePainting(int);
AP_EXTERN_C bool SM64AP_HavePaintingForArea(int, int);
AP_EXTERN_C bool SM64AP_EasyButterflies();
AP_EXTERN_C bool SM64AP_NoDespawn();
AP_EXTERN_C bool SM64AP_PermanentCoinCollection();
AP_EXTERN_C void SM64AP_AssignPermanentCoinSource(
    struct Object *, s16, s16, s16, s16, s16, s16, u32, const void *);
AP_EXTERN_C bool SM64AP_AssignPermanentCoinOutput(struct Object *, struct Object *, int, int);
AP_EXTERN_C bool SM64AP_AssignPermanentAggregateCoinOutput(struct Object *, struct Object *, int);
AP_EXTERN_C void SM64AP_AssignPermanentCoinSlot(struct Object *, struct Object *, int, int);
AP_EXTERN_C bool SM64AP_MarkSpentPermanentCoin(struct Object *, int);
AP_EXTERN_C bool SM64AP_CollectPermanentCoin(struct Object *, int);
AP_EXTERN_C int SM64AP_CollectPermanentCoinOutputs(struct Object *, int, int, int);
AP_EXTERN_C u64 SM64AP_PermanentCoinMask(struct Object *, int, int);
AP_EXTERN_C int SM64AP_CollectedPermanentRedCoins(int);
AP_EXTERN_C void SM64AP_RestorePermanentCoinCount();
AP_EXTERN_C bool SM64AP_ConsumePermanentCoinReconcileRequest();
AP_EXTERN_C bool SM64AP_ShouldSpawnOutstandingCoinStar();
AP_EXTERN_C void SM64AP_FlushPermanentCoinLedger();
AP_EXTERN_C void SM64AP_UpdatePermanentCoinTrap();
AP_EXTERN_C bool SM64AP_ReadyToStart();
AP_EXTERN_C void SM64AP_PrintTitleConnectionStatus();
AP_EXTERN_C void SM64AP_RequestLiveObjectReconcile();
AP_EXTERN_C bool SM64AP_ConsumeLiveObjectReconcileRequest();
AP_EXTERN_C bool SM64AP_DeathLinkPending();
AP_EXTERN_C void SM64AP_DeathLinkClear();
AP_EXTERN_C void SM64AP_DeathLinkSend();
AP_EXTERN_C int SM64AP_CheatItemCount();
AP_EXTERN_C const char *SM64AP_CheatItemName(int);
AP_EXTERN_C bool SM64AP_CheatItemEnabled(int);
AP_EXTERN_C void SM64AP_CheatSetItemEnabled(int, bool);

// Local Moves
AP_EXTERN_C bool SM64AP_CanDoubleJumpForArea(int);
AP_EXTERN_C bool SM64AP_CanDoubleJump();
AP_EXTERN_C bool SM64AP_CanTripleJump();
AP_EXTERN_C bool SM64AP_CanLongJump();
AP_EXTERN_C bool SM64AP_CanBackflip();
AP_EXTERN_C bool SM64AP_CanSideFlip();
AP_EXTERN_C bool SM64AP_CanWallKick();
AP_EXTERN_C bool SM64AP_CanDive();
AP_EXTERN_C bool SM64AP_CanGroundPound();
AP_EXTERN_C bool SM64AP_CanKick();
AP_EXTERN_C bool SM64AP_CanClimb();
AP_EXTERN_C bool SM64AP_CanLedgeGrab();

// Send Item
AP_EXTERN_C int SM64AP_BoxLocationId(int);
AP_EXTERN_C void SM64AP_SendByBoxID(int);
AP_EXTERN_C void SM64AP_SendItem(int);
AP_EXTERN_C int SM64AP_LastLocationCheckId();

// Print Next Message to Screen
AP_EXTERN_C void SM64AP_PrintNext();

// If an item exists on the stack, return it, otherwise 0
AP_EXTERN_C int64_t SM64AP_PopDelayedStack();

// Called on each Bowser stage completion, i is bowser index. Will send StoryComplete depending on completion option.
AP_EXTERN_C void SM64AP_FinishBowser(int i);

// Used to send and receive moat state
AP_EXTERN_C void SM64AP_SetMoatDrained();
AP_EXTERN_C bool SM64AP_MoatDrained();

// Check for switch state (used for initial switch state on level load)
AP_EXTERN_C bool SM64AP_PressedSwitch(int);

#undef AP_EXTERN_C

#endif
